### PR TITLE
bump to v2.0.1 and get rid of the "v" in the versions

### PR DESCRIPTION
**Pull request by basnijholt**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by basnijholt** [comment]
@conda-forge-admin, please rerender

**Comment by basnijholt** [comment]
This will close https://github.com/conda-forge/hpc05-feedstock/issues/8.

**Comment by basnijholt** [comment]
@conda-forge/core conda-smithy isn't doing its job, what can I do?

**Comment by ocefpaf** [comment]
> @conda-forge/core conda-smithy isn't doing its job, what can I do?

https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-with-conda-smithy-locally

**Pull request merged**
